package com.revature.entity;

public class Pet {
    // unique id for each entity
    // this number will be different for every pet, that way we have a way of uniquely identifying each pet
    private int id;
    private String name;
    private String species;
    private String food;

    // default constructor:
    public Pet() {

    }

    // fully parameterized constructor:
    public Pet(int id, String name, String species, String food) {
        this.id = id;
        this.name = name;
        this.species = species;
        this.food = food;
    }

    // a constructor that sets up everything except the id:
    // Why is this important?
    // has to be unique
    // SQL generates these id's for us automatically to be unique
    // when we create a pet object, we don't want to specify an id because it will be generated by the database anyways
    public Pet(String name, String species, String food) {
        this.name = name;
        this.species = species;
        this.food = food;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getFood() {
        return food;
    }

    public void setFood(String food) {
        this.food = food;
    }

    @Override
    public String toString() {
        return "Pet{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", species='" + species + '\'' +
                ", food='" + food + '\'' +
                '}';
    }
}
